version: "3"
services:
  local-mongo:
    image: mongo
    restart: always
    container_name: local-mongo
    networks:
      - local-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # volumes:
    #   - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #   - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"

networks:
  local-mongo:
    external: false